# Generated by Django 2.0.7 on 2018-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='free_meals',
            field=models.IntegerField(choices=[(0, 'Not eligible'), (1, 'Eligible')], default=0, help_text='Select whether customer is eligible for free meals'),
        ),
    ]
