# Generated by Django 2.0.7 on 2018-08-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0002_auto_20180802_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name_plural': 'cash'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['surname', 'first_name'], 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-transaction_time'], 'verbose_name_plural': 'transactions'},
        ),
    ]
