# Generated by Django 2.0.7 on 2018-08-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0004_auto_20180802_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'permissions': (('can_transact', 'Conduct transactions'),), 'verbose_name_plural': 'cash'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['surname', 'first_name'], 'permissions': (('can_set_free_meals', 'Set free meal eligibility'),), 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterField(
            model_name='cash',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='cashless.Customer'),
        ),
    ]
