# Generated by Django 2.0.7 on 2018-09-03 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0010_auto_20180901_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherlink',
            options={'permissions': (('can_assign_voucher', 'Assign vouchers to customers'),)},
        ),
        migrations.AlterField(
            model_name='voucherlink',
            name='last_applied',
            field=models.DateField(default=datetime.datetime(2017, 9, 3, 19, 17, 12, 351813)),
        ),
    ]
