# Generated by Django 2.0.7 on 2018-09-15 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0011_auto_20180903_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['voucher_name'], 'permissions': (('can_add_vouchers', 'Create a new voucher'),)},
        ),
        migrations.AlterField(
            model_name='voucherlink',
            name='last_applied',
            field=models.DateField(default=datetime.datetime(2017, 9, 15, 16, 37, 24, 616234)),
        ),
    ]
