# Generated by Django 2.0.7 on 2018-09-23 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0014_auto_20180920_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'default_permissions': (), 'permissions': (('can_transact', 'Conduct transactions'),), 'verbose_name_plural': 'cash'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'default_permissions': (), 'ordering': ['surname', 'first_name'], 'permissions': (('can_add_customers', 'Create and edit customer accounts'),), 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'ordering': ['-transaction_time'], 'permissions': (('view_finance', 'Can view transaction log'),), 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'default_permissions': (), 'ordering': ['voucher_name'], 'permissions': (('can_add_vouchers', 'Create and edit vouchers'),)},
        ),
        migrations.AlterModelOptions(
            name='voucherlink',
            options={'default_permissions': (), 'permissions': (('can_assign_voucher', 'Assign vouchers to customers'),)},
        ),
        migrations.AlterField(
            model_name='voucherlink',
            name='last_applied',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 13, 49, 56, 74707)),
        ),
    ]
