# Generated by Django 2.0.7 on 2018-09-23 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0015_auto_20180923_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherlink',
            name='last_applied',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 21, 6, 5, 191623)),
        ),
    ]
