# Generated by Django 2.0.7 on 2018-09-26 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0016_auto_20180923_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherlink',
            name='last_applied',
            field=models.DateField(default=datetime.datetime(2017, 9, 26, 18, 4, 5, 422084)),
        ),
    ]
